import { Injectable } from '@angular/core';
import { GoogleGenAI } from '@google/genai';
import { GUIDANCE_SYSTEM_INSTRUCTION } from './prompts';

/**
 * A service that provides AI-powered script analysis and feedback.
 * It uses the Google Gemini API to generate a short, actionable piece of
 * advice for improving a given script text.
 */
@Injectable({ providedIn: 'root' })
export class GuidanceService {
  private readonly ai: GoogleGenAI;

  /**
   * Initializes the GuidanceService.
   * @throws {Error} If the API_KEY environment variable is not set.
   */
  constructor() {
    if (!process.env.API_KEY) {
      throw new Error("API_KEY environment variable not set");
    }
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  }

  /**
   * Analyzes the provided script text and returns a brief, actionable piece of feedback.
   * The feedback is generated by the Gemini model with a specific system instruction
   * to act as a script doctor.
   * @param scriptText The script content to be analyzed.
   * @returns A promise that resolves to a string containing the feedback.
   */
  async getGuidance(scriptText: string): Promise<string> {
    const model = 'gemini-2.5-flash';

    const response = await this.ai.models.generateContent({
      model,
      contents: scriptText,
      config: {
        systemInstruction: GUIDANCE_SYSTEM_INSTRUCTION,
        temperature: 0.8,
        maxOutputTokens: 100,
        thinkingConfig: { thinkingBudget: 50 },
      }
    });

    return response.text.trim();
  }
}
